require("dotenv").config();   // ALWAYS FIRST

const express = require("express");
const mongoose = require("mongoose");
const cors = require("cors");
const path = require("path");
const app = express();
app.use(express.json());
const mongoURI = process.env.MONGO_URI

app.use(cors());


const User = require('./api/userschema.js')
const Promocode = require('./api/promocode.js')

mongoose.connect(mongoURI)
    .then(() => console.log("MongoDB Connected ✅"))
    .catch(err => console.log("Mongo Error:", err));
// Static login folder

app.use(express.static(path.join(__dirname)));

app.get("/adduser", (req, res) => {
    res.sendFile(path.join(__dirname, "../adduser/"))
});

app.get("/", async (req,res)=>{
    res.send("Server is Running")
})

app.post("/add-user", async (req, res) => {
    try {

        const { name, number, gmail, address, position, password, mob } = req.body;
        const newUser = new User({
            name,
            wallet: {
                todayincome: 0,
                yesterdayincome: 0,
                monthly: 0,
                totalincome: 0
            },
            number: number,
            password: password,
            position: position,
            Gmail: gmail,
            address: address,
            Refferal: mob,
            Device: ""

        });
        let saveuser = await newUser.save();

        if (saveuser) {
            await User.updateOne(
                { number: mob },
                {
                    $push: {
                        Customer: {
                            name: name,
                            number: number
                        }
                    }
                }
            );
            res.json({ success: true });
        } else {
            res.json({ success: false });
        }

    } catch (err) {
        console.log(err);
        res.status(500).json({
            success: false,
            message: "Gmail or MObile NUmber is already is Used"
        });
    }
});


app.post("/referlist", async (req, res) => {
    const { number } = req.body
    try {
        const users = await User.findOne(
            { number: number }
        );
        res.json(users);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

/* ✅ GET DATA API */
app.post("/u", async (req, res) => {
    const { usernumber, userpassword } = req.body
    try {
        const users = await User.findOne(
            { number: usernumber }
        );
        res.json(users);
    } catch (error) {
        res.status(500).json({ error: error.message });
    }
});

app.post('/p', async (req, res) => {
    const { usernumber, password, device } = req.body;
    res.json({ usernumber, password, device })
})


app.post('/o', (req, res) => {
    const data = req.body;   // frontend se data
    res.json(data);
});

app.post('/addWallet', async (req, res) => {
    try {
        const { wallet, number } = req.body;

        await User.updateMany(
            { number: number },
            {
                $inc: {
                    "wallet.todayincome": wallet,

                },
                $push: {
                    History: {
                        timestamp: new Date().toLocaleString(),
                        summary: `Commission generated by Voucher Rs ${wallet}`,
                        amount: wallet,
                        status: "Success"
                    }
                }
            }
        );

        res.json({ success: "Done" });

    } catch (err) {
        console.log(err);
        res.status(500).json({ success: false });
    }
});



app.post('/promocode', async (req, res) => {
    try {
        const newCode = new Promocode({      // ✅ CREATE DOCUMENT
            amount: req.body.amount,
            promocode: req.body.promocode,
            time: req.body.ntimes,           // optional if sending
            status: req.body.status,
            transaction: req.body.transaction
        });


        await newCode.save();                // ✅ NOW VALID


        res.json({
            success: true,
            message: "Promocode Saved ✅",
            data: newCode
        });

    } catch (err) {

        res.status(500).json({
            success: false,
            error: err.message
        });
    }
});


app.post('/k', async (req, res) => {
    const { promocode, amount } = req.body
    try {
        const promocode1 = await Promocode.findOne(
            { promocode: promocode }
        );
        res.json(promocode1)

    } catch (err) {
        console.log(err)
    }
})

app.post('/updatewallet', async (req, res) => {
    try {

        const { number, wallet, referwallet, promocode, amount } = req.body;

        const walletAmount = wallet / 10;
        const referralAmount = walletAmount / 10;

        if (!number || !walletAmount)
            return res.json({ success: false, message: "Invalid data ❌" });

        /* ✅ Update User Wallet */
        await User.updateOne(
            { number },
            {
                $inc: {
                    "wallet.todayincome": walletAmount
                },
                $push: {
                    History: {
                        timestamp: new Date().toLocaleString(),
                        summary: `Commission generated by Voucher Rs ${amount} (Code: ${promocode})`,
                        amount: walletAmount,
                        status: "Success"
                    }
                }
            }
        );

        /* ✅ Fetch Updated User */
        const userData = await User.findOne({ number });

        if (!userData)
            return res.json({ success: false, message: "User not found ❌" });

        const referral = userData.Refferal;
        const userkaname = userData.name;

        /* ✅ Referral Bonus */
        if (referral) {
            await User.updateOne(
                { number: referral },
                {
                    $inc: {
                        "wallet.todayincome": referralAmount,
                    },
                    $push: {
                        History: {
                            timestamp: new Date().toLocaleString(),
                            summary: `Commission generated by ${userkaname} (Amount: ₹${walletAmount})`,
                            amount: referralAmount,
                            status: "Success"
                        }
                    }
                }
            );
        }

        /* ✅ Mark Promocode Used */
        await Promocode.updateOne(
            { promocode },
            { $set: { status: "Used" } }
        );

        res.json({
            success: true,
            referral,
            userkaname
        });

    } catch (err) {
        console.log(err);
        res.status(500).json({
            success: false,
            error: err.message
        });
    }
});


app.post('/withdraw', async (req, res) => {
    const { number, position } = req.body
    try {
        const amount = await User.find(
            { number: number }
        )
        res.json(amount)
    } catch (err) {
        console.log(err)
    }
})

app.post('/updateamount', async (req, res) => {
    const { finalamount, number, withdrawAmount } = req.body

    try {
        const users3 = await User.updateMany(
            { number: number },
            {
                $set: { "wallet.todayincome": finalamount },
                $push: {
                    "History": {
                        timestamp: new Date().toLocaleString(),
                        summary: `Please wait , your Withdrawal is  Pending`,
                        amount: withdrawAmount,
                        status: "Pending"
                    }
                }
            }
        );

        if (users3) {
            res.json({ message: "your request is sunmiited" })
        }

    } catch (err) {
        console.log(err)
    }
})


/* ✅ Server */
app.listen(process.env.port, () => {
    console.log("Server Running on Port 5000 🚀");
});



